version: '3'
services:

  web:
    stdin_open: true
    tty: true
    container_name: backend
    command : python manage.py runserver 0.0.0.0:8000
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3305:3306'
    volumes:
      - my-db:/var/lib/mysql
    

volumes:
  my-db:
